import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const hkGrostesk = Hanken_Grotesk({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${hkGrostesk.className} antialiased tracking-[1.56px]`}
      >
        {children}
      </body>
    </html>
  );
}
